kind: Service
apiVersion: v1
metadata:
  name: csi-elastic-block-store-attacher
  labels:
    app: csi-elastic-block-store-attacher
spec:
  selector:
    app: csi-elastic-block-store-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-elastic-block-store-attacher
spec:
  serviceName: "csi-elastic-block-store-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-elastic-block-store-attacher
  template:
    metadata:
      labels:
        app: csi-elastic-block-store-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-elastic-block-storeplugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.4.2
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-elastic-block-store
            type: DirectoryOrCreate
          name: socket-dir
