# WARNING: this is only for testing purposes. Do not install in a production
# cluster.
#
# This exposes the elastic-block-store's Unix domain csi.sock as a TCP port to the
# outside world. The mapping from Unix domain socket to TCP is done
# by socat.
#
# This is useful for testing with csi-sanity or csc.

apiVersion: v1
kind: Service
metadata:
  name: elastic-block-store-service
spec:
  type: NodePort
  selector:
    app: csi-elastic-block-store-socat
  ports:
  - port: 10000 # fixed port inside the pod, dynamically allocated port outside
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-elastic-block-store-socat
spec:
  serviceName: "csi-elastic-block-store-socat"
  replicas: 1
  selector:
    matchLabels:
      app: csi-elastic-block-store-socat
  template:
    metadata:
      labels:
        app: csi-elastic-block-store-socat
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-elastic-block-storeplugin
            topologyKey: kubernetes.io/hostname
      containers:
        - name: socat
          image: alpine/socat:1.0.3
          args:
            - tcp-listen:10000,fork,reuseaddr
            - unix-connect:/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-elastic-block-store
            type: DirectoryOrCreate
          name: socket-dir
